"""add price list

Revision ID: be6e8cbab5ed
Revises: 0a676924c9e8
Create Date: 2024-10-03 10:11:00.181846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'be6e8cbab5ed'
down_revision: Union[str, None] = '0a676924c9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.Unicode(), nullable=True),
        sa.Column('upload_data', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_lists')
    # ### end Alembic commands ###
