"""change the upload of the product image

Revision ID: d66d8da7dfc1
Revises: 1b2e2156ed2c
Create Date: 2024-10-11 07:43:51.002601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66d8da7dfc1'
down_revision: Union[str, None] = '1b2e2156ed2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('image_name', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('products', 'image_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('products_images')
    # ### end Alembic commands ###
