"""change the upload of the news image and information about us

Revision ID: 2418c7958333
Revises: d66d8da7dfc1
Create Date: 2024-10-14 00:16:32.724372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2418c7958333'
down_revision: Union[str, None] = 'd66d8da7dfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('about_us_id', sa.Integer(), nullable=False),
        sa.Column('image_name', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['about_us_id'], ['main_content.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('news_id', sa.Integer(), nullable=False),
        sa.Column('news_image_name', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('main_content', 'about_us_image')
    op.drop_column('news', 'news_image_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('main_content', sa.Column('about_us_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('news_images')
    op.drop_table('about_us_images')
    # ### end Alembic commands ###
